### ISSUE TITLE
loudevents: ValueError: Length mismatch: Expected axis has 73 elements, new values have 72 elements

### ISSUE THREAD

**Issue by gjoseph92** [gjoseph92/soundDB#16]
In [LOUDEVENTS_DENAUDAL.txt](https://github.com/gjoseph92/soundDB/files/628642/LOUDEVENTS_DENAUDAL.txt)

This is probably just an oddity of the file (haven't looked yet), but it should be handled more gracefully.

Here's a random file that does seem valid: 
[LOUDEVENTS_DENAFANG.txt](https://github.com/gjoseph92/soundDB/files/628644/LOUDEVENTS_DENAFANG.txt)

```
Error while parsing "E:2010 DENAUDAL Upper Dall Glacier\02 ANALYSIS\SPL Analysis\LOUDEVENTS_DENAUDAL.txt":
Traceback (most recent call last):
  File "C:\Users\gljoseph\dev\soundDB\soundDB\accessor.py", line 473, in iterate
    data = self.parse(entry, state= state) if state is not None else self.parse(entry)
  File "C:\Users\gljoseph\dev\soundDB\soundDB\parsers.py", line 327, in parse
    data.columns = list(range(24)) * 3
  File "C:\Users\gljoseph\AppData\Local\Continuum\Miniconda3\envs\soundDB\lib\site-packages\pandas\core\generic.py", lin
e 2371, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\src\properties.pyx", line 65, in pandas.lib.AxisProperty.__set__ (pandas\lib.c:45002)
  File "C:\Users\gljoseph\AppData\Local\Continuum\Miniconda3\envs\soundDB\lib\site-packages\pandas\core\generic.py", lin
e 425, in _set_axis
    self._data.set_axis(axis, labels)
  File "C:\Users\gljoseph\AppData\Local\Continuum\Miniconda3\envs\soundDB\lib\site-packages\pandas\core\internals.py", l
ine 2572, in set_axis
    'new values have %d elements' % (old_len, new_len))
ValueError: Length mismatch: Expected axis has 73 elements, new values have 72 elements
```

**Comment by dbetchkal** [comment]
Turns out there was an extra column in _"LOUDEVENTS_DENAUDAL.txt"_ that was presumably calculated Lnat levels. Removing that allows the file to be parsed. I don't think this is an actual concern of ours, and I'll close the issue.
